### ISSUE TITLE
User notification with alert details

### ISSUE THREAD

**Issue by IRTermite** [bfosberry/GameSocial#27]
Pop-up notification when users/friends login, starts/joins game, sends requests, etc.

**Comment by bfosberry** [comment]
socket.io looks like a great candidate for this. Can add a simple modal with dismissable events that pops up when things happen. Finally, I'll have to create event streams for each user, and push friends event streams with each of these events

**Comment by bfosberry** [comment]
Splitting whats left of this up into different tasks
