### ISSUE TITLE
User notification alert detail, Join Game

### ISSUE THREAD

**Issue by IRTermite** [bfosberry/GameSocial#28]
Hyperlink on user notification popup, "Join Game", that allows user to join their friend's game in-progress.

Of course, won't work with XBox Live or PSN, but will work for Steam or Origin since you are already playing on a PC.

Mobile apps are excluded for obvious reasons, but maybe there could be an agent  hook to open the game on your PC, from your phone?

**Comment by bfosberry** [comment]
This is a lot more doable now, chat servers have a vendor agnostic launch_url, and game servers have a steam launch url also.
